/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tablas;

import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author danyc
 */
public class TablaReservadas extends javax.swing.JFrame {
    /*Crear tabla con modelo*/
    private DefaultTableModel m = new DefaultTableModel();
    private String[] res= {
                "@abajo","@acelerar","@adelante","@apagar","arreglo","@arriba","@atras",
                "booleano","cadena","@calibrar","@captura","caracter","@cargar","ciclo",
                "corto","decimal","declaracion","@derecha","@detener","@direccionar",
                "@ejecutar","@encender","entero","@esperar","falso","@fijo", 
                "fin","funcion","@girar ","@haz","@imprimir","iniciar","@izquierda",
                "@largo","@leer","mientras","no","nulo","@parav","@pin","principal","@regresa", 
                "@retorno","@ruta","@seguir","si","@video","verdadero"
                };
    private String[] desc={
      "Desciende altitud del dron","Aumenta o Disminuye la velocidad","Mueve el dron a su frente","Detiene las helices del dron", 
        "Declara arreglos","Aumenta altitud del dron","Mueve el dron a su reverso","Define variable Booleana",
        "Define variable de Cadena","Calibra funcionamiento de helices","Tomar fotografia","Define variable de caracter","Implementa librerias","Implementa for",
        "Define variable numerico corto","Define variable punto flotante corto","Define lista de variables","Mueve el dron a su derecha","Detiene y Descende el dron",
        "Mueve el dron en direccion elegible","Llama y ejecuta a una funcion","Enciende helices","Define variable numerica entera",
        "Hace el dron esperar en milisegundos","Valor Booleano Falso","Suspende dron en ubicacion actual","Final de ciclo si/si no",
        "Define una funcion de usuario","Inclina el dron en grados","Ejecuta un mientras 1 o mas veces","Imprime el valor de una variable en consola",
        "Inicia seccion cargar librerias","Mueve el dron a su izquierda","Define variable numerica larga","Lee valores de una terminal a variable",
        "Ciclo que corre en base a condicion","Combinado con si para condicion opuesta","Define un valor nulo","Detiene grabacion video",
        "Se comunica con un pin microcontrolador","Define seccion de logica","Regresa el dron a punto origen","Retorna valor de variable",
        "Define una navegacion en base a coordenadas","Dron continua en direccion dada por tiempo dado","Definir ciclo condicional",
        "Empieza grabacion video","Valor verdadero booleano"
        
    
    };
    public TablaReservadas() {
        initComponents();
        setLocationRelativeTo(null);
        m = (DefaultTableModel) Palabras.getModel();               
        /*JLabel palabras[] = new JLabel[res.length];*/        
        /*Poner numero filas*/       
        for (int i = 0;i<res.length;i++) {
            m.addRow(new Object[]{res[i],desc[i]});            
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Palabras = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Palabras Reservadas");

        Palabras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Palabra Reservada", "Funcion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Palabras);
        if (Palabras.getColumnModel().getColumnCount() > 0) {
            Palabras.getColumnModel().getColumn(0).setResizable(false);
            Palabras.getColumnModel().getColumn(1).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 672, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TablaReservadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TablaReservadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TablaReservadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TablaReservadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TablaReservadas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Palabras;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
