/* The following code was generated by JFlex 1.4.3 on 22/05/21 10:35 */

package analizador;
import java.io.*;
import static analizador.Tokens.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 22/05/21 10:35 from the specification file
 * <tt>C:/analizador/src/analizador/Lexer.flex</tt>
 */
class Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\13\1\14\2\0\1\13\22\0\1\13\1\0\1\0\2\0"+
    "\1\21\1\17\1\0\1\23\1\24\1\12\1\2\1\0\1\3\1\4"+
    "\1\16\12\1\1\27\1\22\1\26\1\15\1\25\1\0\1\6\32\11"+
    "\4\0\1\10\1\0\1\35\1\45\1\34\1\36\1\5\1\40\1\50"+
    "\1\51\1\37\1\47\1\7\1\46\1\43\1\30\1\33\1\44\1\53"+
    "\1\32\1\42\1\31\1\41\1\54\3\7\1\52\1\0\1\20\uff83\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\1\1\2\1\3\1\4\1\1\1\5\1\6\1\5"+
    "\1\1\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\17\5\1\0"+
    "\1\2\1\10\1\24\4\5\1\25\1\26\25\5\1\27"+
    "\13\5\1\0\35\5\1\30\6\5\1\31\4\5\1\32"+
    "\2\5\1\33\1\0\5\5\1\34\2\5\1\35\27\5"+
    "\1\36\4\5\1\37\1\5\1\40\13\5\1\41\5\5"+
    "\1\42\1\43\5\5\1\44\10\5\1\45\4\5\1\46"+
    "\1\5\1\47\1\50\1\5\1\51\1\5\1\52\6\5"+
    "\1\53\1\54\3\5\1\55\2\5\1\56\11\5\1\57"+
    "\6\5\1\60\1\5\1\61\1\62\1\5\1\63\1\5"+
    "\1\64\2\5\1\65\1\66\1\67\2\5\1\70\2\5"+
    "\1\71\5\5\1\72\1\73\1\74\1\75\1\76\1\77"+
    "\2\5\1\100\1\5\1\101\1\5\1\102\4\5\1\103"+
    "\1\104\1\105\4\5\1\106\1\107\25\5";

  private static int [] zzUnpackAction() {
    int [] result = new int[316];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\55\0\132\0\207\0\264\0\341\0\u010e\0\55"+
    "\0\u013b\0\u0168\0\55\0\55\0\u0195\0\55\0\55\0\55"+
    "\0\55\0\55\0\55\0\55\0\55\0\55\0\55\0\u01c2"+
    "\0\u01ef\0\u021c\0\u0249\0\u0276\0\u02a3\0\u02d0\0\u02fd\0\u032a"+
    "\0\u0357\0\u0384\0\u03b1\0\u03de\0\u040b\0\u0438\0\341\0\207"+
    "\0\u0465\0\u0492\0\u04bf\0\u04ec\0\u0519\0\u0546\0\55\0\u04bf"+
    "\0\u0573\0\u05a0\0\u05cd\0\u05fa\0\u0627\0\u0654\0\u0681\0\u06ae"+
    "\0\u06db\0\u0708\0\u0735\0\u0762\0\u078f\0\u07bc\0\u07e9\0\u0816"+
    "\0\u0843\0\u0870\0\u089d\0\u08ca\0\u08f7\0\u04bf\0\u0924\0\u0951"+
    "\0\u097e\0\u09ab\0\u09d8\0\u0a05\0\u0a32\0\u0a5f\0\u0a8c\0\u0ab9"+
    "\0\u0ae6\0\u0b13\0\u0b40\0\u0b6d\0\u0b9a\0\u0bc7\0\u0bf4\0\u0c21"+
    "\0\u0c4e\0\u0c7b\0\u0ca8\0\u0cd5\0\u0d02\0\u0d2f\0\u0d5c\0\u0d89"+
    "\0\u0db6\0\u0de3\0\u0e10\0\u0e3d\0\u0e6a\0\u0e97\0\u0ec4\0\u0ef1"+
    "\0\u0f1e\0\u0f4b\0\u0f78\0\u0fa5\0\u0fd2\0\u0fff\0\u102c\0\u0b40"+
    "\0\u1059\0\u1086\0\u10b3\0\u10e0\0\u110d\0\u113a\0\u0b40\0\u1167"+
    "\0\u1194\0\u11c1\0\u11ee\0\u0b40\0\u121b\0\u1248\0\u1275\0\u1275"+
    "\0\u12a2\0\u12cf\0\u12fc\0\u1329\0\u1356\0\u12a2\0\u1383\0\u13b0"+
    "\0\u12a2\0\u13dd\0\u140a\0\u1437\0\u1464\0\u1491\0\u14be\0\u14eb"+
    "\0\u1518\0\u1545\0\u1572\0\u159f\0\u15cc\0\u15f9\0\u1626\0\u1653"+
    "\0\u1680\0\u16ad\0\u16da\0\u1707\0\u1734\0\u1761\0\u178e\0\u17bb"+
    "\0\u12a2\0\u17e8\0\u1815\0\u1842\0\u186f\0\u189c\0\u18c9\0\u12a2"+
    "\0\u18f6\0\u1923\0\u1950\0\u197d\0\u19aa\0\u19d7\0\u1a04\0\u1a31"+
    "\0\u1a5e\0\u1a8b\0\u1ab8\0\u19aa\0\u1ae5\0\u1b12\0\u1b3f\0\u1b6c"+
    "\0\u1b99\0\u19aa\0\u19aa\0\u1bc6\0\u1bf3\0\u1c20\0\u1c4d\0\u1c7a"+
    "\0\u19aa\0\u1ca7\0\u1cd4\0\u1d01\0\u1d2e\0\u1d5b\0\u1d88\0\u1db5"+
    "\0\u1de2\0\u19aa\0\u1e0f\0\u1e3c\0\u1e69\0\u1e96\0\u19aa\0\u1ec3"+
    "\0\u19aa\0\u19aa\0\u1ef0\0\u19aa\0\u1f1d\0\u1f1d\0\u1f4a\0\u1f77"+
    "\0\u1fa4\0\u1fd1\0\u1ffe\0\u202b\0\u1f1d\0\u1f1d\0\u2058\0\u2085"+
    "\0\u20b2\0\u1f1d\0\u20df\0\u210c\0\u1f1d\0\u2139\0\u2166\0\u2193"+
    "\0\u21c0\0\u21ed\0\u221a\0\u2247\0\u2274\0\u22a1\0\u1f1d\0\u22ce"+
    "\0\u22fb\0\u2328\0\u2355\0\u2382\0\u23af\0\u2382\0\u23dc\0\u2382"+
    "\0\u2382\0\u2409\0\u2382\0\u2436\0\u2382\0\u2463\0\u2490\0\u2382"+
    "\0\u2382\0\u2382\0\u24bd\0\u24ea\0\u2382\0\u2517\0\u2544\0\u2382"+
    "\0\u2571\0\u259e\0\u25cb\0\u25f8\0\u2625\0\u2625\0\u2625\0\u2625"+
    "\0\u2625\0\u2625\0\u2625\0\u2652\0\u267f\0\u2625\0\u26ac\0\u2625"+
    "\0\u26d9\0\u2625\0\u2706\0\u2733\0\u2760\0\u278d\0\u2733\0\u2733"+
    "\0\u2733\0\u27ba\0\u27e7\0\u2814\0\u2841\0\u2841\0\u2841\0\u286e"+
    "\0\u289b\0\u28c8\0\u28f5\0\u2922\0\u294f\0\u297c\0\u29a9\0\u29d6"+
    "\0\u2a03\0\u2a30\0\u2a5d\0\u2a8a\0\u2ab7\0\u2ae4\0\u2b11\0\u2b3e"+
    "\0\u2b6b\0\u2b98\0\u2bc5\0\u0168";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[316];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\2\12\1\13\2\14\1\15\1\16\1\17\1\20\1\21"+
    "\1\22\1\23\1\24\1\25\1\26\1\27\1\30\1\11"+
    "\1\31\1\11\1\32\1\33\1\34\1\35\1\36\1\11"+
    "\1\37\1\40\1\41\1\42\1\43\1\11\1\44\1\45"+
    "\2\11\1\46\56\0\1\3\2\0\1\47\1\12\1\0"+
    "\3\12\16\0\25\12\1\0\1\50\2\0\1\47\51\0"+
    "\1\50\1\0\1\51\1\47\51\0\1\52\54\0\1\53"+
    "\3\0\1\53\1\0\2\53\1\12\16\0\1\54\11\53"+
    "\1\55\4\53\1\56\5\53\1\0\1\53\3\0\1\53"+
    "\1\0\2\53\1\12\16\0\25\53\1\0\1\12\3\0"+
    "\1\12\1\0\3\12\16\0\25\12\15\0\1\57\40\0"+
    "\1\53\3\0\1\53\1\0\2\53\1\12\16\0\3\53"+
    "\1\60\5\53\1\61\13\53\1\0\1\53\3\0\1\62"+
    "\1\0\2\53\1\12\16\0\11\53\1\63\13\53\1\0"+
    "\1\53\3\0\1\53\1\0\2\53\1\12\16\0\3\53"+
    "\1\64\1\53\1\65\1\53\1\66\15\53\1\0\1\53"+
    "\3\0\1\53\1\0\2\53\1\12\16\0\1\53\1\67"+
    "\1\70\1\53\1\71\1\53\1\72\5\53\1\73\1\74"+
    "\7\53\1\0\1\53\3\0\1\75\1\0\2\53\1\12"+
    "\16\0\7\53\1\76\15\53\1\0\1\53\3\0\1\53"+
    "\1\0\2\53\1\12\16\0\1\77\12\53\1\100\6\53"+
    "\1\101\2\53\1\0\1\53\3\0\1\53\1\0\2\53"+
    "\1\12\16\0\5\53\1\102\1\53\1\103\1\53\1\104"+
    "\13\53\1\0\1\53\3\0\1\105\1\0\2\53\1\12"+
    "\16\0\7\53\1\106\15\53\1\0\1\53\3\0\1\53"+
    "\1\0\2\53\1\12\16\0\7\53\1\107\15\53\1\0"+
    "\1\53\3\0\1\53\1\0\2\53\1\12\16\0\2\53"+
    "\1\110\2\53\1\111\1\53\1\112\15\53\1\0\1\53"+
    "\3\0\1\53\1\0\2\53\1\12\16\0\3\53\1\113"+
    "\21\53\1\0\1\53\3\0\1\114\1\0\2\53\1\12"+
    "\16\0\5\53\1\115\17\53\1\0\1\53\3\0\1\53"+
    "\1\0\2\53\1\12\16\0\7\53\1\116\15\53\1\0"+
    "\1\53\3\0\1\53\1\0\2\53\1\12\16\0\5\53"+
    "\1\117\17\53\1\0\1\53\3\0\1\120\1\0\2\53"+
    "\1\12\16\0\7\53\1\121\15\53\14\51\1\0\40\51"+
    "\1\0\1\52\3\0\1\122\50\0\1\123\3\0\1\123"+
    "\1\0\2\123\1\12\16\0\25\123\1\0\1\123\3\0"+
    "\1\123\1\0\2\123\1\12\16\0\1\123\1\124\2\123"+
    "\1\125\20\123\1\0\1\123\3\0\1\123\1\0\2\123"+
    "\1\12\16\0\14\123\1\126\10\123\1\0\1\123\3\0"+
    "\1\127\1\0\2\123\1\12\16\0\25\123\1\0\1\123"+
    "\3\0\1\123\1\0\2\123\1\12\16\0\16\123\1\130"+
    "\6\123\1\0\1\123\3\0\1\123\1\0\2\123\1\12"+
    "\16\0\1\123\1\131\16\123\1\132\4\123\1\0\1\123"+
    "\3\0\1\123\1\0\2\123\1\12\16\0\1\123\1\133"+
    "\23\123\1\0\1\123\3\0\1\123\1\0\2\123\1\12"+
    "\16\0\2\123\1\134\22\123\1\0\1\123\3\0\1\123"+
    "\1\0\2\123\1\12\16\0\2\123\1\135\3\123\1\136"+
    "\5\123\1\137\1\123\1\140\6\123\1\0\1\123\3\0"+
    "\1\123\1\0\2\123\1\12\16\0\4\123\1\141\20\123"+
    "\1\0\1\123\3\0\1\123\1\0\2\123\1\12\16\0"+
    "\2\123\1\142\22\123\1\0\1\123\3\0\1\123\1\0"+
    "\2\123\1\12\16\0\2\123\1\143\22\123\1\0\1\123"+
    "\3\0\1\144\1\0\2\123\1\12\16\0\25\123\1\0"+
    "\1\123\3\0\1\145\1\0\2\123\1\12\16\0\25\123"+
    "\1\0\1\123\3\0\1\123\1\0\2\123\1\12\16\0"+
    "\5\123\1\146\17\123\1\0\1\123\3\0\1\123\1\0"+
    "\2\123\1\12\16\0\5\123\1\147\17\123\1\0\1\123"+
    "\3\0\1\123\1\0\2\123\1\12\16\0\1\123\1\150"+
    "\1\151\1\123\1\152\20\123\1\0\1\123\3\0\1\123"+
    "\1\0\2\123\1\12\16\0\2\123\1\153\22\123\1\0"+
    "\1\123\3\0\1\123\1\0\2\123\1\12\16\0\7\123"+
    "\1\154\15\123\1\0\1\123\3\0\1\123\1\0\2\123"+
    "\1\12\16\0\14\123\1\155\10\123\1\0\1\123\3\0"+
    "\1\123\1\0\2\123\1\12\16\0\23\123\1\156\1\123"+
    "\1\0\1\123\3\0\1\123\1\0\2\123\1\12\16\0"+
    "\16\123\1\157\6\123\1\0\1\123\3\0\1\123\1\0"+
    "\2\123\1\12\16\0\1\160\16\123\1\161\5\123\1\0"+
    "\1\123\3\0\1\123\1\0\2\123\1\12\16\0\1\162"+
    "\24\123\1\0\1\123\3\0\1\123\1\0\2\123\1\12"+
    "\16\0\20\123\1\163\4\123\1\0\1\123\3\0\1\164"+
    "\1\0\2\123\1\12\16\0\25\123\1\0\1\123\3\0"+
    "\1\123\1\0\2\123\1\12\16\0\7\123\1\165\15\123"+
    "\1\0\1\123\3\0\1\123\1\0\2\123\1\12\16\0"+
    "\2\123\1\166\22\123\1\0\1\123\3\0\1\123\1\0"+
    "\2\123\1\12\16\0\1\167\24\123\1\0\1\123\3\0"+
    "\1\123\1\0\2\123\1\12\16\0\3\123\1\170\21\123"+
    "\1\0\1\123\3\0\1\171\1\0\2\123\1\12\16\0"+
    "\25\123\1\0\1\123\3\0\1\123\1\0\2\123\1\12"+
    "\16\0\2\123\1\172\22\123\1\0\1\123\3\0\1\123"+
    "\1\0\2\123\1\12\16\0\2\123\1\173\22\123\1\0"+
    "\1\123\3\0\1\123\1\0\2\123\1\12\16\0\22\123"+
    "\1\174\2\123\1\0\1\123\3\0\1\123\1\0\2\123"+
    "\1\12\16\0\2\123\1\175\22\123\1\0\1\123\3\0"+
    "\1\123\1\0\2\123\1\12\16\0\6\123\1\176\16\123"+
    "\1\0\1\177\2\200\52\0\1\201\3\0\1\201\1\0"+
    "\2\201\1\12\16\0\25\201\1\0\1\201\3\0\1\202"+
    "\1\0\2\201\1\12\16\0\25\201\1\0\1\201\3\0"+
    "\1\203\1\0\2\201\1\12\16\0\25\201\1\0\1\201"+
    "\3\0\1\204\1\0\2\201\1\12\16\0\25\201\1\0"+
    "\1\201\3\0\1\201\1\0\2\201\1\12\16\0\4\201"+
    "\1\205\20\201\1\0\1\201\3\0\1\201\1\0\2\201"+
    "\1\12\16\0\3\201\1\206\21\201\1\0\1\201\3\0"+
    "\1\201\1\0\2\201\1\12\16\0\3\201\1\207\21\201"+
    "\1\0\1\201\3\0\1\201\1\0\2\201\1\12\16\0"+
    "\2\201\1\210\22\201\1\0\1\201\3\0\1\201\1\0"+
    "\2\201\1\12\16\0\5\201\1\211\17\201\1\0\1\201"+
    "\3\0\1\201\1\0\2\201\1\12\16\0\1\201\1\212"+
    "\23\201\1\0\1\201\3\0\1\201\1\0\2\201\1\12"+
    "\16\0\5\201\1\213\12\201\1\214\4\201\1\0\1\201"+
    "\3\0\1\215\1\0\2\201\1\12\16\0\25\201\1\0"+
    "\1\201\3\0\1\201\1\0\2\201\1\12\16\0\1\201"+
    "\1\216\23\201\1\0\1\201\3\0\1\201\1\0\2\201"+
    "\1\12\16\0\7\201\1\217\15\201\1\0\1\201\3\0"+
    "\1\201\1\0\2\201\1\12\16\0\16\201\1\220\6\201"+
    "\1\0\1\201\3\0\1\201\1\0\2\201\1\12\16\0"+
    "\5\201\1\221\17\201\1\0\1\201\3\0\1\222\1\0"+
    "\2\201\1\12\16\0\7\201\1\223\15\201\1\0\1\201"+
    "\3\0\1\201\1\0\2\201\1\12\16\0\16\201\1\224"+
    "\6\201\1\0\1\201\3\0\1\201\1\0\2\201\1\12"+
    "\16\0\16\201\1\225\6\201\1\0\1\201\3\0\1\201"+
    "\1\0\2\201\1\12\16\0\20\201\1\226\4\201\1\0"+
    "\1\201\3\0\1\201\1\0\2\201\1\12\16\0\17\201"+
    "\1\227\5\201\1\0\1\201\3\0\1\230\1\0\2\201"+
    "\1\12\16\0\25\201\1\0\1\201\3\0\1\231\1\0"+
    "\2\201\1\12\16\0\25\201\1\0\1\201\3\0\1\201"+
    "\1\0\2\201\1\12\16\0\7\201\1\232\6\201\1\233"+
    "\6\201\1\0\1\201\3\0\1\234\1\0\2\201\1\12"+
    "\16\0\25\201\1\0\1\201\3\0\1\201\1\0\2\201"+
    "\1\12\16\0\4\201\1\235\20\201\1\0\1\201\3\0"+
    "\1\201\1\0\2\201\1\12\16\0\2\201\1\236\22\201"+
    "\1\0\1\201\3\0\1\201\1\0\2\201\1\12\16\0"+
    "\11\201\1\237\13\201\1\0\1\201\3\0\1\201\1\0"+
    "\2\201\1\12\16\0\12\201\1\240\12\201\1\0\1\201"+
    "\3\0\1\201\1\0\2\201\1\12\16\0\3\201\1\241"+
    "\21\201\1\0\1\201\3\0\1\201\1\0\2\201\1\12"+
    "\16\0\4\201\1\242\20\201\1\0\1\201\3\0\1\201"+
    "\1\0\2\201\1\12\16\0\11\201\1\243\13\201\1\0"+
    "\1\201\3\0\1\201\1\0\2\201\1\12\16\0\1\244"+
    "\24\201\1\0\1\201\3\0\1\201\1\0\2\201\1\12"+
    "\16\0\1\245\24\201\1\0\1\201\3\0\1\201\1\0"+
    "\2\201\1\12\16\0\5\201\1\246\17\201\1\0\1\201"+
    "\3\0\1\201\1\0\2\201\1\12\16\0\16\201\1\247"+
    "\6\201\1\0\1\201\3\0\1\201\1\0\2\201\1\12"+
    "\16\0\2\201\1\250\22\201\1\0\1\201\3\0\1\201"+
    "\1\0\2\201\1\12\16\0\20\201\1\251\4\201\1\0"+
    "\1\201\3\0\1\201\1\0\2\201\1\12\16\0\5\201"+
    "\1\252\17\201\1\0\1\201\3\0\1\201\1\0\2\201"+
    "\1\12\16\0\6\201\1\253\16\201\1\0\1\201\3\0"+
    "\1\254\1\0\2\201\1\12\16\0\25\201\1\0\1\177"+
    "\54\0\1\255\3\0\1\255\1\0\2\255\1\12\16\0"+
    "\25\255\1\0\1\255\3\0\1\255\1\0\2\255\1\12"+
    "\16\0\2\255\1\256\22\255\1\0\1\255\3\0\1\255"+
    "\1\0\2\255\1\12\16\0\1\257\24\255\1\0\1\255"+
    "\3\0\1\255\1\0\2\255\1\12\16\0\2\255\1\260"+
    "\22\255\1\0\1\255\3\0\1\255\1\0\2\255\1\12"+
    "\16\0\11\255\1\261\13\255\1\0\1\255\3\0\1\255"+
    "\1\0\2\255\1\12\16\0\2\255\1\262\22\255\1\0"+
    "\1\255\3\0\1\263\1\0\2\255\1\12\16\0\25\255"+
    "\1\0\1\255\3\0\1\255\1\0\2\255\1\12\16\0"+
    "\3\255\1\264\21\255\1\0\1\255\3\0\1\255\1\0"+
    "\2\255\1\12\16\0\4\255\1\265\20\255\1\0\1\255"+
    "\3\0\1\255\1\0\2\255\1\12\16\0\5\255\1\266"+
    "\17\255\1\0\1\255\3\0\1\255\1\0\2\255\1\12"+
    "\16\0\1\267\24\255\1\0\1\255\3\0\1\255\1\0"+
    "\2\255\1\12\16\0\11\255\1\270\13\255\1\0\1\255"+
    "\3\0\1\255\1\0\2\255\1\12\16\0\15\255\1\271"+
    "\7\255\1\0\1\255\3\0\1\255\1\0\2\255\1\12"+
    "\16\0\3\255\1\272\21\255\1\0\1\255\3\0\1\255"+
    "\1\0\2\255\1\12\16\0\12\255\1\273\12\255\1\0"+
    "\1\255\3\0\1\255\1\0\2\255\1\12\16\0\20\255"+
    "\1\274\4\255\1\0\1\255\3\0\1\255\1\0\2\255"+
    "\1\12\16\0\15\255\1\275\7\255\1\0\1\255\3\0"+
    "\1\276\1\0\2\255\1\12\16\0\25\255\1\0\1\255"+
    "\3\0\1\255\1\0\2\255\1\12\16\0\5\255\1\277"+
    "\17\255\1\0\1\255\3\0\1\255\1\0\2\255\1\12"+
    "\16\0\5\255\1\300\17\255\1\0\1\255\3\0\1\255"+
    "\1\0\2\255\1\12\16\0\3\255\1\301\21\255\1\0"+
    "\1\255\3\0\1\255\1\0\2\255\1\12\16\0\1\302"+
    "\24\255\1\0\1\255\3\0\1\255\1\0\2\255\1\12"+
    "\16\0\4\255\1\303\20\255\1\0\1\255\3\0\1\255"+
    "\1\0\2\255\1\12\16\0\13\255\1\304\11\255\1\0"+
    "\1\255\3\0\1\255\1\0\2\255\1\12\16\0\5\255"+
    "\1\305\17\255\1\0\1\255\3\0\1\255\1\0\2\255"+
    "\1\12\16\0\4\255\1\306\20\255\1\0\1\255\3\0"+
    "\1\255\1\0\2\255\1\12\16\0\7\255\1\307\15\255"+
    "\1\0\1\255\3\0\1\255\1\0\2\255\1\12\16\0"+
    "\7\255\1\310\15\255\1\0\1\255\3\0\1\255\1\0"+
    "\2\255\1\12\16\0\7\255\1\311\15\255\1\0\1\255"+
    "\3\0\1\255\1\0\2\255\1\12\16\0\3\255\1\312"+
    "\21\255\1\0\1\255\3\0\1\255\1\0\2\255\1\12"+
    "\16\0\7\255\1\313\15\255\1\0\1\255\3\0\1\255"+
    "\1\0\2\255\1\12\16\0\7\255\1\314\15\255\1\0"+
    "\1\255\3\0\1\255\1\0\2\255\1\12\16\0\1\255"+
    "\1\315\23\255\1\0\1\255\3\0\1\255\1\0\2\255"+
    "\1\12\16\0\4\255\1\316\20\255\1\0\1\255\3\0"+
    "\1\255\1\0\2\255\1\12\16\0\24\255\1\317\1\0"+
    "\1\255\3\0\1\320\1\0\2\255\1\12\16\0\25\255"+
    "\1\0\1\255\3\0\1\255\1\0\2\255\1\12\16\0"+
    "\3\255\1\321\21\255\1\0\1\255\3\0\1\255\1\0"+
    "\2\255\1\12\16\0\2\255\1\322\22\255\1\0\1\255"+
    "\3\0\1\255\1\0\2\255\1\12\16\0\5\255\1\323"+
    "\17\255\1\0\1\255\3\0\1\255\1\0\2\255\1\12"+
    "\16\0\3\255\1\324\21\255\1\0\1\325\3\0\1\325"+
    "\1\0\2\325\1\12\16\0\25\325\1\0\1\325\3\0"+
    "\1\325\1\0\2\325\1\12\16\0\3\325\1\326\21\325"+
    "\1\0\1\325\3\0\1\325\1\0\2\325\1\12\16\0"+
    "\6\325\1\327\16\325\1\0\1\325\3\0\1\325\1\0"+
    "\2\325\1\12\16\0\5\325\1\330\17\325\1\0\1\325"+
    "\3\0\1\325\1\0\2\325\1\12\16\0\1\325\1\331"+
    "\23\325\1\0\1\325\3\0\1\325\1\0\2\325\1\12"+
    "\16\0\1\332\24\325\1\0\1\325\3\0\1\325\1\0"+
    "\2\325\1\12\16\0\12\325\1\333\12\325\1\0\1\325"+
    "\3\0\1\325\1\0\2\325\1\12\16\0\1\325\1\334"+
    "\23\325\1\0\1\325\3\0\1\325\1\0\2\325\1\12"+
    "\16\0\2\325\1\335\22\325\1\0\1\325\3\0\1\325"+
    "\1\0\2\325\1\12\16\0\5\325\1\336\17\325\1\0"+
    "\1\325\3\0\1\325\1\0\2\325\1\12\16\0\2\325"+
    "\1\337\22\325\1\0\1\325\3\0\1\325\1\0\2\325"+
    "\1\12\16\0\2\325\1\340\22\325\1\0\1\325\3\0"+
    "\1\325\1\0\2\325\1\12\16\0\16\325\1\341\6\325"+
    "\1\0\1\325\3\0\1\325\1\0\2\325\1\12\16\0"+
    "\5\325\1\342\17\325\1\0\1\325\3\0\1\325\1\0"+
    "\2\325\1\12\16\0\2\325\1\343\22\325\1\0\1\325"+
    "\3\0\1\325\1\0\2\325\1\12\16\0\1\344\24\325"+
    "\1\0\1\325\3\0\1\325\1\0\2\325\1\12\16\0"+
    "\2\325\1\345\22\325\1\0\1\325\3\0\1\346\1\0"+
    "\2\325\1\12\16\0\25\325\1\0\1\325\3\0\1\325"+
    "\1\0\2\325\1\12\16\0\21\325\1\347\3\325\1\0"+
    "\1\325\3\0\1\325\1\0\2\325\1\12\16\0\5\325"+
    "\1\350\17\325\1\0\1\325\3\0\1\325\1\0\2\325"+
    "\1\12\16\0\2\325\1\351\22\325\1\0\1\325\3\0"+
    "\1\325\1\0\2\325\1\12\16\0\4\325\1\352\20\325"+
    "\1\0\1\325\3\0\1\325\1\0\2\325\1\12\16\0"+
    "\5\325\1\353\17\325\1\0\1\325\3\0\1\325\1\0"+
    "\2\325\1\12\16\0\13\325\1\354\11\325\1\0\1\325"+
    "\3\0\1\355\1\0\2\325\1\12\16\0\25\325\1\0"+
    "\1\325\3\0\1\325\1\0\2\325\1\12\16\0\3\325"+
    "\1\356\21\325\1\0\1\325\3\0\1\325\1\0\2\325"+
    "\1\12\16\0\2\325\1\357\22\325\1\0\1\325\3\0"+
    "\1\325\1\0\2\325\1\12\16\0\2\325\1\360\22\325"+
    "\1\0\1\325\3\0\1\325\1\0\2\325\1\12\16\0"+
    "\7\325\1\361\15\325\1\0\1\325\3\0\1\325\1\0"+
    "\2\325\1\12\16\0\5\325\1\362\17\325\1\0\1\325"+
    "\3\0\1\325\1\0\2\325\1\12\16\0\6\325\1\363"+
    "\16\325\1\0\1\364\3\0\1\364\1\0\2\364\1\12"+
    "\16\0\25\364\1\0\1\364\3\0\1\365\1\0\2\364"+
    "\1\12\16\0\25\364\1\0\1\364\3\0\1\364\1\0"+
    "\2\364\1\12\16\0\2\364\1\366\22\364\1\0\1\364"+
    "\3\0\1\364\1\0\2\364\1\12\16\0\5\364\1\367"+
    "\17\364\1\0\1\364\3\0\1\364\1\0\2\364\1\12"+
    "\16\0\3\364\1\370\21\364\1\0\1\364\3\0\1\364"+
    "\1\0\2\364\1\12\16\0\5\364\1\371\17\364\1\0"+
    "\1\364\3\0\1\372\1\0\2\364\1\12\16\0\25\364"+
    "\1\0\1\364\3\0\1\364\1\0\2\364\1\12\16\0"+
    "\5\364\1\373\17\364\1\0\1\364\3\0\1\364\1\0"+
    "\2\364\1\12\16\0\5\364\1\374\17\364\1\0\1\364"+
    "\3\0\1\364\1\0\2\364\1\12\16\0\3\364\1\375"+
    "\21\364\1\0\1\364\3\0\1\364\1\0\2\364\1\12"+
    "\16\0\5\364\1\376\17\364\1\0\1\364\3\0\1\364"+
    "\1\0\2\364\1\12\16\0\1\364\1\377\23\364\1\0"+
    "\1\364\3\0\1\364\1\0\2\364\1\12\16\0\2\364"+
    "\1\u0100\22\364\1\0\1\364\3\0\1\364\1\0\2\364"+
    "\1\12\16\0\5\364\1\u0101\17\364\1\0\1\364\3\0"+
    "\1\364\1\0\2\364\1\12\16\0\16\364\1\u0102\6\364"+
    "\1\0\1\364\3\0\1\364\1\0\2\364\1\12\16\0"+
    "\5\364\1\u0103\17\364\1\0\1\364\3\0\1\364\1\0"+
    "\2\364\1\12\16\0\7\364\1\u0104\15\364\1\0\1\364"+
    "\3\0\1\364\1\0\2\364\1\12\16\0\2\364\1\u0105"+
    "\22\364\1\0\1\364\3\0\1\364\1\0\2\364\1\12"+
    "\16\0\7\364\1\u0106\15\364\1\0\1\364\3\0\1\364"+
    "\1\0\2\364\1\12\16\0\2\364\1\u0107\22\364\1\0"+
    "\1\364\3\0\1\364\1\0\2\364\1\12\16\0\1\u0108"+
    "\24\364\1\0\1\364\3\0\1\364\1\0\2\364\1\12"+
    "\16\0\5\364\1\u0109\17\364\1\0\1\364\3\0\1\364"+
    "\1\0\2\364\1\12\16\0\14\364\1\u010a\10\364\1\0"+
    "\1\364\3\0\1\364\1\0\2\364\1\12\16\0\1\u010b"+
    "\24\364\1\0\1\364\3\0\1\u010c\1\0\2\364\1\12"+
    "\16\0\25\364\1\0\1\u010d\3\0\1\u010d\1\0\2\u010d"+
    "\1\12\16\0\25\u010d\1\0\1\u010d\3\0\1\u010d\1\0"+
    "\2\u010d\1\12\16\0\2\u010d\1\u010e\22\u010d\1\0\1\u010d"+
    "\3\0\1\u010d\1\0\2\u010d\1\12\16\0\2\u010d\1\u010f"+
    "\22\u010d\1\0\1\u010d\3\0\1\u010d\1\0\2\u010d\1\12"+
    "\16\0\2\u010d\1\u0110\22\u010d\1\0\1\u010d\3\0\1\u010d"+
    "\1\0\2\u010d\1\12\16\0\2\u010d\1\u0111\22\u010d\1\0"+
    "\1\u010d\3\0\1\u010d\1\0\2\u010d\1\12\16\0\2\u010d"+
    "\1\u0112\22\u010d\1\0\1\u010d\3\0\1\u0113\1\0\2\u010d"+
    "\1\12\16\0\25\u010d\1\0\1\u010d\3\0\1\u010d\1\0"+
    "\2\u010d\1\12\16\0\4\u010d\1\u0114\20\u010d\1\0\1\u010d"+
    "\3\0\1\u010d\1\0\2\u010d\1\12\16\0\3\u010d\1\u0115"+
    "\21\u010d\1\0\1\u010d\3\0\1\u010d\1\0\2\u010d\1\12"+
    "\16\0\2\u010d\1\u0116\22\u010d\1\0\1\u010d\3\0\1\u010d"+
    "\1\0\2\u010d\1\12\16\0\6\u010d\1\u0117\16\u010d\1\0"+
    "\1\u010d\3\0\1\u010d\1\0\2\u010d\1\12\16\0\12\u010d"+
    "\1\u0118\12\u010d\1\0\1\u010d\3\0\1\u010d\1\0\2\u010d"+
    "\1\12\16\0\5\u010d\1\u0119\17\u010d\1\0\1\u010d\3\0"+
    "\1\u010d\1\0\2\u010d\1\12\16\0\3\u010d\1\u011a\21\u010d"+
    "\1\0\1\u010d\3\0\1\u010d\1\0\2\u010d\1\12\16\0"+
    "\2\u010d\1\u011b\22\u010d\1\0\1\u011c\3\0\1\u011c\1\0"+
    "\2\u011c\1\12\16\0\25\u011c\1\0\1\u011c\3\0\1\u011c"+
    "\1\0\2\u011c\1\12\16\0\7\u011c\1\u011d\15\u011c\1\0"+
    "\1\u011c\3\0\1\u011c\1\0\2\u011c\1\12\16\0\1\u011e"+
    "\24\u011c\1\0\1\u011c\3\0\1\u011c\1\0\2\u011c\1\12"+
    "\16\0\5\u011c\1\u011f\17\u011c\1\0\1\u011c\3\0\1\u011c"+
    "\1\0\2\u011c\1\12\16\0\16\u011c\1\u0120\6\u011c\1\0"+
    "\1\u011c\3\0\1\u011c\1\0\2\u011c\1\12\16\0\3\u011c"+
    "\1\u0121\21\u011c\1\0\1\u0122\3\0\1\u0122\1\0\2\u0122"+
    "\1\12\16\0\25\u0122\1\0\1\u0122\3\0\1\u0122\1\0"+
    "\2\u0122\1\12\16\0\3\u0122\1\u0123\21\u0122\1\0\1\u0122"+
    "\3\0\1\u0122\1\0\2\u0122\1\12\16\0\5\u0122\1\u0124"+
    "\17\u0122\1\0\1\u0125\3\0\1\u0125\1\0\2\u0125\1\12"+
    "\16\0\25\u0125\1\0\1\u0125\3\0\1\u0125\1\0\2\u0125"+
    "\1\12\16\0\1\u0126\24\u0125\1\0\1\u0125\3\0\1\u0125"+
    "\1\0\2\u0125\1\12\16\0\2\u0125\1\u0127\22\u0125\1\0"+
    "\1\u0128\3\0\1\u0128\1\0\2\u0128\1\12\16\0\25\u0128"+
    "\1\0\1\u0129\3\0\1\u0129\1\0\2\u0129\1\12\16\0"+
    "\25\u0129\1\0\1\u012a\3\0\1\u012a\1\0\2\u012a\1\12"+
    "\16\0\25\u012a\1\0\1\u012b\3\0\1\u012b\1\0\2\u012b"+
    "\1\12\16\0\25\u012b\1\0\1\u012c\3\0\1\u012c\1\0"+
    "\2\u012c\1\12\16\0\25\u012c\1\0\1\u012d\3\0\1\u012d"+
    "\1\0\2\u012d\1\12\16\0\25\u012d\1\0\1\u012e\3\0"+
    "\1\u012e\1\0\2\u012e\1\12\16\0\25\u012e\1\0\1\u012f"+
    "\3\0\1\u012f\1\0\2\u012f\1\12\16\0\25\u012f\1\0"+
    "\1\u0130\3\0\1\u0130\1\0\2\u0130\1\12\16\0\25\u0130"+
    "\1\0\1\u0131\3\0\1\u0131\1\0\2\u0131\1\12\16\0"+
    "\25\u0131\1\0\1\u0132\3\0\1\u0132\1\0\2\u0132\1\12"+
    "\16\0\25\u0132\1\0\1\u0133\3\0\1\u0133\1\0\2\u0133"+
    "\1\12\16\0\25\u0133\1\0\1\u0134\3\0\1\u0134\1\0"+
    "\2\u0134\1\12\16\0\25\u0134\1\0\1\u0135\3\0\1\u0135"+
    "\1\0\2\u0135\1\12\16\0\25\u0135\1\0\1\u0136\3\0"+
    "\1\u0136\1\0\2\u0136\1\12\16\0\25\u0136\1\0\1\u0137"+
    "\3\0\1\u0137\1\0\2\u0137\1\12\16\0\25\u0137\1\0"+
    "\1\u0138\3\0\1\u0138\1\0\2\u0138\1\12\16\0\25\u0138"+
    "\1\0\1\u0139\3\0\1\u0139\1\0\2\u0139\1\12\16\0"+
    "\25\u0139\1\0\1\u013a\3\0\1\u013a\1\0\2\u013a\1\12"+
    "\16\0\25\u013a\1\0\1\u013b\3\0\1\u013b\1\0\2\u013b"+
    "\1\12\16\0\25\u013b\1\0\1\u013c\3\0\1\u013c\1\0"+
    "\2\u013c\1\12\16\0\25\u013c";

  private static int [] zzUnpackTrans() {
    int [] result = new int[11250];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\1\1\11\5\1\1\11\2\1\2\11\1\1\12\11"+
    "\17\1\1\0\7\1\1\11\42\1\1\0\55\1\1\0"+
    "\274\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[316];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    public String lexeme;
    InformacionAnalisis c = new InformacionAnalisis();


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 120) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Tokens yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 63: 
          { c.linea=yyline; lexeme=yytext(); return RESERVADA_ADELANTE;
          }
        case 72: break;
        case 53: 
          { c.linea=yyline; lexeme=yytext(); return RESERVADA_DETENER;
          }
        case 73: break;
        case 1: 
          { c.linea=yyline; lexeme=yytext(); return ERROR;
          }
        case 74: break;
        case 18: 
          { c.linea=yyline; lexeme=yytext(); return MENOR;
          }
        case 75: break;
        case 14: 
          { c.linea=yyline; lexeme=yytext(); return PUNTO_COMA;
          }
        case 76: break;
        case 50: 
          { c.linea=yyline; lexeme=yytext(); return RESERVADA_REGRESA;
          }
        case 77: break;
        case 52: 
          { c.linea=yyline; lexeme=yytext(); return RESERVADA_ARREGLO;
          }
        case 78: break;
        case 31: 
          { c.linea=yyline; lexeme=yytext(); return RESERVADA_PARA;
          }
        case 79: break;
        case 11: 
          { c.linea=yyline; lexeme=yytext(); return Y;
          }
        case 80: break;
        case 69: 
          { c.linea=yyline; lexeme=yytext(); return RESERVADA_VERDADERO;
          }
        case 81: break;
        case 71: 
          { c.linea=yyline; lexeme=yytext(); return RESERVADA_DIRECCIONAR;
          }
        case 82: break;
        case 34: 
          { c.linea=yyline; lexeme=yytext(); return RESERVADA_CICLO;
          }
        case 83: break;
        case 48: 
          { c.linea=yyline; lexeme=yytext(); return RESERVADA_ESPERAR;
          }
        case 84: break;
        case 41: 
          { c.linea=yyline; lexeme=yytext(); return RESERVADA_VIDEO;
          }
        case 85: break;
        case 55: 
          { c.linea=yyline; lexeme=yytext(); return RESERVADA_DECIMAL;
          }
        case 86: break;
        case 38: 
          { c.linea=yyline; lexeme=yytext(); return RESERVADA_PARAV;
          }
        case 87: break;
        case 7: 
          { c.linea=yyline; lexeme=yytext(); return POR;
          }
        case 88: break;
        case 20: 
          { c.linea=yyline; lexeme=yytext(); return NUMERO_DECIMAL;
          }
        case 89: break;
        case 35: 
          { c.linea=yyline; lexeme=yytext(); return RESERVADA_ATRAS;
          }
        case 90: break;
        case 3: 
          { c.linea=yyline; lexeme=yytext(); return MAS;
          }
        case 91: break;
        case 6: 
          { c.linea=yyline; lexeme=yytext(); return ARROBA;
          }
        case 92: break;
        case 13: 
          { c.linea=yyline; lexeme=yytext(); return MODULO;
          }
        case 93: break;
        case 66: 
          { c.linea=yyline; lexeme=yytext(); return RESERVADA_BOOLEANO;
          }
        case 94: break;
        case 19: 
          { c.linea=yyline; lexeme=yytext(); return DOS_PUNTOS;
          }
        case 95: break;
        case 12: 
          { c.linea=yyline; lexeme=yytext(); return O;
          }
        case 96: break;
        case 47: 
          { c.linea=yyline; lexeme=yytext(); return RESERVADA_SEGUIR;
          }
        case 97: break;
        case 27: 
          { c.linea=yyline; lexeme=yytext(); return NUMERO_EXPONENTE;
          }
        case 98: break;
        case 60: 
          { c.linea=yyline; lexeme=yytext(); return RESERVADA_CARACTER;
          }
        case 99: break;
        case 10: 
          { c.linea=yyline; lexeme=yytext(); return DIVISION;
          }
        case 100: break;
        case 61: 
          { c.linea=yyline; lexeme=yytext(); return RESERVADA_CALIBRAR;
          }
        case 101: break;
        case 43: 
          { c.linea=yyline; lexeme=yytext(); return RESERVADA_CARGAR;
          }
        case 102: break;
        case 36: 
          { c.linea=yyline; lexeme=yytext(); return RESERVADA_ABAJO;
          }
        case 103: break;
        case 62: 
          { c.linea=yyline; lexeme=yytext(); return RESERVADA_ACELERAR;
          }
        case 104: break;
        case 22: 
          { c.linea=yyline; lexeme=yytext(); return RESERVADA_NO;
          }
        case 105: break;
        case 45: 
          { c.linea=yyline; lexeme=yytext(); return RESERVADA_ARRIBA;
          }
        case 106: break;
        case 30: 
          { c.linea=yyline; lexeme=yytext(); return RESERVADA_FIJO;
          }
        case 107: break;
        case 44: 
          { c.linea=yyline; lexeme=yytext(); return RESERVADA_CADENA;
          }
        case 108: break;
        case 59: 
          { c.linea=yyline; lexeme=yytext(); return RESERVADA_EJECUTAR;
          }
        case 109: break;
        case 9: 
          { c.linea=yyline; lexeme=yytext(); return ASIGNACION;
          }
        case 110: break;
        case 29: 
          { c.linea=yyline; lexeme=yytext(); return RESERVADA_RUTA;
          }
        case 111: break;
        case 26: 
          { c.linea=yyline; lexeme=yytext(); return RESERVADA_HAZ;
          }
        case 112: break;
        case 5: 
          { c.linea=yyline; lexeme=yytext(); return IDENTIFICADOR;
          }
        case 113: break;
        case 65: 
          { c.linea=yyline; lexeme=yytext(); return RESERVADA_MIENTRAS;
          }
        case 114: break;
        case 40: 
          { c.linea=yyline; lexeme=yytext(); return RESERVADA_GIRAR;
          }
        case 115: break;
        case 67: 
          { c.linea=yyline; lexeme=yytext(); return RESERVADA_IZQUIERDA;
          }
        case 116: break;
        case 51: 
          { c.linea=yyline; lexeme=yytext(); return RESERVADA_CAPTURA;
          }
        case 117: break;
        case 2: 
          { c.linea=yyline; lexeme=yytext(); return NUMERO;
          }
        case 118: break;
        case 54: 
          { c.linea=yyline; lexeme=yytext(); return RESERVADA_DERECHA;
          }
        case 119: break;
        case 17: 
          { c.linea=yyline; lexeme=yytext(); return MAYOR;
          }
        case 120: break;
        case 64: 
          { c.linea=yyline; lexeme=yytext(); return RESERVADA_IMPRIMIR;
          }
        case 121: break;
        case 58: 
          { c.linea=yyline; lexeme=yytext(); return RESERVADA_ENCENDER;
          }
        case 122: break;
        case 56: 
          { c.linea=yyline; lexeme=yytext(); return RESERVADA_INICIAR;
          }
        case 123: break;
        case 39: 
          { c.linea=yyline; lexeme=yytext(); return RESERVADA_LARGO;
          }
        case 124: break;
        case 24: 
          { c.linea=yyline; lexeme=yytext(); return RESERVADA_FIN;
          }
        case 125: break;
        case 33: 
          { c.linea=yyline; lexeme=yytext(); return RESERVADA_CORTO;
          }
        case 126: break;
        case 4: 
          { c.linea=yyline; lexeme=yytext(); return MENOS;
          }
        case 127: break;
        case 57: 
          { c.linea=yyline; lexeme=yytext(); return RESERVADA_FUNCION;
          }
        case 128: break;
        case 37: 
          { c.linea=yyline; lexeme=yytext(); return RESERVADA_FALSO;
          }
        case 129: break;
        case 42: 
          { c.linea=yyline; lexeme=yytext(); return RESERVADA_ENTERO;
          }
        case 130: break;
        case 32: 
          { c.linea=yyline; lexeme=yytext(); return RESERVADA_LEER;
          }
        case 131: break;
        case 15: 
          { c.linea=yyline; lexeme=yytext(); return PARENTESIS_IZQ;
          }
        case 132: break;
        case 25: 
          { c.linea=yyline; lexeme=yytext(); return RESERVADA_PIN;
          }
        case 133: break;
        case 68: 
          { c.linea=yyline; lexeme=yytext(); return RESERVADA_PRINCIPAL;
          }
        case 134: break;
        case 23: 
          { c.linea=yyline; lexeme=yytext(); return RESERVADA_SI;
          }
        case 135: break;
        case 46: 
          { c.linea=yyline; lexeme=yytext(); return RESERVADA_APAGAR;
          }
        case 136: break;
        case 16: 
          { c.linea=yyline; lexeme=yytext(); return PARENTESIS_DER;
          }
        case 137: break;
        case 70: 
          { c.linea=yyline; lexeme=yytext(); return RESERVADA_DECLARACION;
          }
        case 138: break;
        case 21: 
          { c.linea=yyline; lexeme=yytext(); return IGUAL;
          }
        case 139: break;
        case 8: 
          { /*Ignore*/
          }
        case 140: break;
        case 49: 
          { c.linea=yyline; lexeme=yytext(); return RESERVADA_RETORNO;
          }
        case 141: break;
        case 28: 
          { c.linea=yyline; lexeme=yytext(); return RESERVADA_NULO;
          }
        case 142: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return null;
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
