
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Jun 19 23:34:15 MDT 2021
//----------------------------------------------------

package analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RESERVADA_SI = 29;
  public static final int RESERVADA_PRINCIPAL = 28;
  public static final int RESERVADA_DECLARACION = 24;
  public static final int OP_ARITMETICO2 = 18;
  public static final int OP_ARITMETICO1 = 17;
  public static final int OP_RELACIONAL = 20;
  public static final int RESERVADA_DECIMAL = 11;
  public static final int RESERVADA_ENTERO = 10;
  public static final int ERROR = 16;
  public static final int RESERVADA_MIENTRAS = 27;
  public static final int PARENTESIS_IZQ = 22;
  public static final int NUMERO_DECIMAL = 4;
  public static final int PARENTESIS_DER = 21;
  public static final int DOS_PUNTOS = 15;
  public static final int RESERVADA_FIN = 25;
  public static final int ASIGNACION = 14;
  public static final int RESERVADA_INICIAR = 26;
  public static final int RESERVADA_CADENA = 8;
  public static final int EOF = 0;
  public static final int CADENA_TEXTO = 6;
  public static final int error = 1;
  public static final int NUMERO = 3;
  public static final int RESERVADA_VERDADERO = 12;
  public static final int IDENTIFICADOR = 2;
  public static final int NUMERO_EXPONENTE = 5;
  public static final int PUNTO_COMA = 23;
  public static final int OP_LOGICO = 19;
  public static final int RESERVADA_BOOLEANO = 7;
  public static final int RESERVADA_CORTO = 9;
  public static final int RESERVADA_FALSO = 13;
}

