
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Jun 22 19:16:07 MDT 2021
//----------------------------------------------------

package analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUMERO = 3;
  public static final int RESERVADA_CORTO = 9;
  public static final int PARENTESIS_IZQ = 30;
  public static final int ESPECIALES_SOLAS = 18;
  public static final int CADENA_TEXTO = 6;
  public static final int DOS_PUNTOS = 16;
  public static final int IDENTIFICADOR = 2;
  public static final int RESERVADA_SI = 43;
  public static final int RESERVADA_VERDADERO = 12;
  public static final int ESPECIALES_PARAMETRO = 22;
  public static final int RESERVADA_MIENTRAS = 39;
  public static final int ESPECIALES_DOS = 21;
  public static final int ESPECIALES_CT = 20;
  public static final int PUNTO_COMA = 31;
  public static final int OP_RELACIONAL = 26;
  public static final int EOF = 0;
  public static final int PARENTESIS_DER = 29;
  public static final int RESERVADA_FALSO = 13;
  public static final int RESERVADA_LLAMAR = 38;
  public static final int error = 1;
  public static final int COMA = 15;
  public static final int RESERVADA_ENTERO = 10;
  public static final int RESERVADA_FIN = 34;
  public static final int RESERVADA_DECLARACION = 33;
  public static final int RESERVADA_FUNCION = 35;
  public static final int ERROR = 17;
  public static final int ASIGNACION = 14;
  public static final int ESPECIALES_ID = 19;
  public static final int OP_ARITMETICO2 = 24;
  public static final int NUMERO_DECIMAL = 4;
  public static final int OP_LOGICO = 25;
  public static final int RESERVADA_PRINCIPAL = 41;
  public static final int ESPECIALES_RUTA = 23;
  public static final int RESERVADA_HAZ = 36;
  public static final int OP_MAS = 27;
  public static final int RESERVADA_BOOLEANO = 7;
  public static final int RESERVADA_NO = 40;
  public static final int RESERVADA_INICIAR = 37;
  public static final int RESERVADA_RETORNO = 42;
  public static final int NUMERO_EXPONENTE = 5;
  public static final int RESERVADA_CICLO = 32;
  public static final int OP_MENOS = 28;
  public static final int RESERVADA_DECIMAL = 11;
  public static final int RESERVADA_CADENA = 8;
}

