
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Jun 19 17:23:41 MDT 2021
//----------------------------------------------------

package analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RESERVADA_SI = 28;
  public static final int RESERVADA_PRINCIPAL = 27;
  public static final int RESERVADA_DECLARACION = 21;
  public static final int OP_ARITMETICO2 = 11;
  public static final int OP_ARITMETICO1 = 10;
  public static final int OP_RELACIONAL = 13;
  public static final int RESERVADA_DECIMAL = 20;
  public static final int RESERVADA_ENTERO = 22;
  public static final int ERROR = 5;
  public static final int RESERVADA_MIENTRAS = 26;
  public static final int NUMERO_DECIMAL = 8;
  public static final int PARENTESIS_IZQ = 15;
  public static final int DOS_PUNTOS = 4;
  public static final int PARENTESIS_DER = 14;
  public static final int RESERVADA_FIN = 23;
  public static final int ASIGNACION = 2;
  public static final int RESERVADA_INICIAR = 25;
  public static final int RESERVADA_CADENA = 18;
  public static final int EOF = 0;
  public static final int CADENA_TEXTO = 3;
  public static final int error = 1;
  public static final int NUMERO = 7;
  public static final int RESERVADA_VERDADERO = 29;
  public static final int IDENTIFICADOR = 6;
  public static final int NUMERO_EXPONENTE = 9;
  public static final int PUNTO_COMA = 16;
  public static final int RESERVADA_CORTO = 19;
  public static final int RESERVADA_BOOLEANO = 17;
  public static final int OP_LOGICO = 12;
  public static final int RESERVADA_FALSO = 24;
}

