/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package analizador;

import analizador.TablaSimbolos;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Map;
import java.util.Stack;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import modelos.Simbolos;

/**
 *
 * @author danyc
 */
public class TablaIdentificadores extends javax.swing.JFrame {
    
    private static ArrayList<Simbolos> simbolos = new ArrayList<Simbolos>();
    private DefaultTableModel m = new DefaultTableModel();

    static Map<String, TablaSimbolos> tablaSimbolos;
    static Stack<String> lista;
    
    public TablaIdentificadores(ArrayList<Simbolos> simbolos) {
        this.simbolos = simbolos;
        limpiar();
        initComponents();
        setIconImage(new ImageIcon("C:\\analizador\\src\\img\\icono.png").getImage());
        setLocationRelativeTo(null);
        jTable1.setAutoCreateRowSorter(true);
        m = (DefaultTableModel) jTable1.getModel();
        ArrayList<Simbolos> nuevo = reorganizar(simbolos);
        for (Simbolos sim : nuevo) {
            if(!sim.getComponente().equals("IDENTIFICADOR"))
                continue;
            m.addRow(new Object[]{sim.getLinea(), "",sim.getLexema(), ""});
        }
        String mezcla = "";
        int suma = 0;
        Collection<analizador.Simbolo> sim =  TablaSimbolos.enviarLista();
        for (int i = 0; i < m.getRowCount(); i++) {
            for (analizador.Simbolo simbolo : sim) {
                         
                if(simbolo.nombre.equals(m.getValueAt(i, 2).toString())){
                    m.setValueAt(simbolo.tipo, i, 1);
                    m.setValueAt(simbolo.nombre, i, 2);
                    m.setValueAt(simbolo.valor, i, 3);
                    m.setValueAt(simbolo.clase, i, 4);
                }
            }
        }
//        int r = m.getRowCount()-1;
//        for (int i = 0; i < r; i++) {
//            if(m.getValueAt(i, 1).toString().equals("")){
//                System.err.println(i+". Dentro, "+m.getValueAt(i, 2).toString());
//                m.removeRow(i);            
//            }
//        }
//        for (Simbolo simbolo : sim) {
//            if(simbolo.tipo.equals("cadena"))
//                    mezcla += simbolo.valor.toString();                
//                if(simbolo.tipo.equals("entero"))
//                    suma += Integer.parseInt(simbolo.valor.toString());       
//        }
//        System.out.println("Mezcla: "+mezcla+", Suma: "+suma);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbl_Icono = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tabla de Identificadores");

        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Línea", "Tipo", "Lexema", "Valor", "Clase"
            }
        ));
        jTable1.setRowHeight(25);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        jPanel2.setBackground(new java.awt.Color(102, 153, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Identificadores");
        jLabel1.setName("lbl_Titulo"); // NOI18N

        lbl_Icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono_65.png"))); // NOI18N
        lbl_Icono.setText("___");
        lbl_Icono.setName("lbl_Icono"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_Icono, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Icono, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 737, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TablaIdentificadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TablaIdentificadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TablaIdentificadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TablaIdentificadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TablaIdentificadores(simbolos).setVisible(true);
            }
        });
    }
    
    private ArrayList<Simbolos> reorganizar(ArrayList<Simbolos> array){
        ArrayList<Simbolos> n_simbolos = new ArrayList<>();
        for (Simbolos sim : array) {
            boolean agregar = true;
            if(sim.getComponente().equalsIgnoreCase("IDENTIFICADOR")){
                for (int j = 0; j < n_simbolos.size(); j++) {
                    if(sim.getLexema().equals(n_simbolos.get(j).getLexema()))
                        agregar = false;
                }
            }
            if(agregar)
                n_simbolos.add(sim);
        }
        return n_simbolos;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl_Icono;
    // End of variables declaration//GEN-END:variables

    private void limpiar(){
        int r = m.getRowCount();
        for (int i = 0; i < r; i++) {
            m.removeRow(r);            
        }
    }      
}

