package analizador;


public enum Tokens {
    MAS,
    MENOS,
    IGUAL,
    POR,
    DIVISION,
    ASIGNACION,
    Y,
    O,
    MODULO,
    PUNTO_COMA,
    PARENTESIS_IZQ,
    PARENTESIS_DER,
    MAYOR,
    MENOR,
    DOS_PUNTOS,
    RESERVADA_SI,
    RESERVADA_NO,
    RESERVADA_PARA,
    RESERVADA_MIENTRAS,
    RESERVADA_ENTERO,
    RESERVADA_CADENA,
    RESERVADA_BOOLEANO,
    RESERVADA_PRINCIPAL,
    RESERVADA_FUNCION,
    RESERVADA_INICIAR,
    RESERVADA_FIN,
    NUMERO,
    IDENTIFICADOR,
    ERROR
    
}
